baseURL = 'http://www.hacimuro.com/'
languageCode = 'en-gb'
title = "Haci's Debugging Adventures"
theme = "nightfall"

[params]
author = "Haci Muro"
user = "debug"
hostname = "hacimuro.com"
showrss = true
published = false
readingTime = true
nextprev = true


[[params.social]]
key = 0
name = "github"
url = "https://github.com/murat-U-Saglam"
icon = "fa-brands fa-github fa-lg"

[[params.social]]
key = 1
name = "X"
url = "https://twitter.com/MuratUSaglam"
icon = "fa-brands fa-x-twitter fa-lg"

[[params.social]]
key = 2
name = "linkedin"
url = "https://www.linkedin.com/in/murat-saglam/"
icon = "fa-brands fa-linkedin fa-lg"

[[params.social]]
key = 3
name = "email"
url = "mailto:muratusaglam@gmail.com"
icon = "fa-solid fa-envelope fa-lg"


[menu]
[[menu.header]]
name = "blog"
weight = 0
url = "blog"
[[menu.header]]
name = "projects"
weight = 2
url = "projects"
[[menu.header]]
name = "about"
weight = 1
url = "about"
