baseURL = 'http://www.hacimuro.com/'
languageCode = 'en-gb'
title = "Haci's Debugging Adventures"
theme = "nightfall"

[params]
author = "Haci Muro"
user = "debug"
hostname = "hacimuro.com"
published = false
readingTime = true
nextprev = true
footerHtml = 'CC-0, Haci Muro | Built with <a href="https://gohugo.io" class="footerLink">Hugo</a>'

[[params.social]]
key = 0
name = "github"
url = "https://github.com/murat-U-Saglam"
icon = "fa-brands fa-github"


[[params.social]]
key = 1
name = "X"
url = "https://twitter.com/MuratUSaglam"
icon = "fa-brands fa-x-twitter"

[[params.social]]
key = 2
name = "linkedin"
url = "https://www.linkedin.com/in/murat-saglam/"
icon = "fa-brands fa-linkedin"

[[params.social]]
key = 3
name = "email"
url = "mailto:muratusaglam@gmail.com"
icon = "fa-solid fa-envelope"


[menu]
[[menu.header]]
name = "blog"
weight = 0
url = "blog"
[[menu.header]]
name = "projects"
weight = 2
url = "projects"
[[menu.header]]
name = "about"
weight = 1
url = "about"
